Algoritmo "Média"
// Disciplina  : [Linguagem e Lógica de programação]
// Professor  : Joandson Silva
// Desorição  : Aqui  você descreve o que o programa faz!  (Função)
// Autor(a)   : Nome do(a) aluno(a)
// Data atual : 06/02/2023
Var
// Seção de Declarações das variáveis
         Media, P1, P2, P3, P4: real
      aluno: caracter
Inicio
// Seção de comandos, procedimentos, funções, operadores, etc...
          Escreva("Digite o nome da(o) aluna(o): ")
      Leia




















