Algoritmo "SemNome"
//
//
// Descrição  : Aqui você descreve oque o programa faz: (função)
// Autor(a)   : Nome do(a) aluno(a)
// Data atual : 14/08/2024
Var
  num1, num2, Resultado: Inteiro
  
  
Inicio
   Escreva("Digite o primeiro numero")
   Leia(num1)
   Escreva("Digite o segundo numero")
   Leia(num2)
   Escreva("Digite o terceiro numero")
   Leia(num3)
     Resultado <- (num1 - num2)
      Escreva("O resultado é;" , resultado)
      
      
FimAlgoritmo